//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, {
  AxiosError,
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  CancelToken
} from "axios";

import moment from "moment";

export class AccountClientServiceProxy {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? "";
  }

  /**
   * 登录
   * @param body (optional)
   * @return Success
   */
  login(
    body: AccountLoginDto | undefined,
    cancelToken?: CancelToken
  ): Promise<AuthenticateResultModelApiResponse> {
    let url_ = this.baseUrl + "/api/AccountClient/Login";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processLogin(_response);
      });
  }

  protected processLogin(
    response: AxiosResponse
  ): Promise<AuthenticateResultModelApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = AuthenticateResultModelApiResponse.fromJS(resultData200);
      return Promise.resolve<AuthenticateResultModelApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<AuthenticateResultModelApiResponse>(null as any);
  }

  /**
   * 刷新token
   * @param refreshToken (optional)
   * @return Success
   */
  refreshToken(
    refreshToken: string | undefined,
    cancelToken?: CancelToken
  ): Promise<AuthenticateResultModelApiResponse> {
    let url_ = this.baseUrl + "/api/AccountClient/RefreshToken?";
    if (refreshToken === null)
      throw new Error("The parameter 'refreshToken' cannot be null.");
    else if (refreshToken !== undefined)
      url_ += "refreshToken=" + encodeURIComponent("" + refreshToken) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "POST",
      url: url_,
      headers: {
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRefreshToken(_response);
      });
  }

  protected processRefreshToken(
    response: AxiosResponse
  ): Promise<AuthenticateResultModelApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = AuthenticateResultModelApiResponse.fromJS(resultData200);
      return Promise.resolve<AuthenticateResultModelApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<AuthenticateResultModelApiResponse>(null as any);
  }
}

export class FileServiceProxy {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? "";
  }

  /**
   * 文件控制器
   * @return Success
   */
  getFile(cancelToken?: CancelToken): Promise<StringApiResponse> {
    let url_ = this.baseUrl + "/api/File/GetFile";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetFile(_response);
      });
  }

  protected processGetFile(
    response: AxiosResponse
  ): Promise<StringApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = StringApiResponse.fromJS(resultData200);
      return Promise.resolve<StringApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<StringApiResponse>(null as any);
  }
}

export class OrgUnitNodeServiceProxy {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? "";
  }

  /**
   * 创建或更新组织机构节点信息
   * @param body (optional)
   * @return Success - No return data
   */
  createOrUpdate(
    body: CreateOrUpdateOrgUnitNodeInput | undefined,
    cancelToken?: CancelToken
  ): Promise<void> {
    let url_ = this.baseUrl + "/api/OrgUnitNode/CreateOrUpdate";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCreateOrUpdate(_response);
      });
  }

  protected processCreateOrUpdate(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * 删除组织机构节点信息
   * @param body (optional)
   * @return Success - No return data
   */
  delete(
    body: EntityDto | undefined,
    cancelToken?: CancelToken
  ): Promise<void> {
    let url_ = this.baseUrl + "/api/OrgUnitNode/Delete";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "DELETE",
      url: url_,
      headers: {
        "Content-Type": "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDelete(_response);
      });
  }

  protected processDelete(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * 获取组织机构节点编辑信息
   * @param id (optional)
   * @return Success
   */
  getForEdit(
    id: string | undefined,
    cancelToken?: CancelToken
  ): Promise<OrgUnitNodeForEditOutputApiResponse> {
    let url_ = this.baseUrl + "/api/OrgUnitNode/GetForEdit?";
    if (id === null) throw new Error("The parameter 'id' cannot be null.");
    else if (id !== undefined)
      url_ += "Id=" + encodeURIComponent("" + id) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetForEdit(_response);
      });
  }

  protected processGetForEdit(
    response: AxiosResponse
  ): Promise<OrgUnitNodeForEditOutputApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = OrgUnitNodeForEditOutputApiResponse.fromJS(resultData200);
      return Promise.resolve<OrgUnitNodeForEditOutputApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<OrgUnitNodeForEditOutputApiResponse>(null as any);
  }

  /**
   * 获取树数据
   * @param orgUnitNodeId (optional)
   * @param parentOrgUnitNodeId (optional)
   * @param filterText (optional)
   * @param sorting (optional)
   * @param maxResultCount (optional)
   * @param skipCount (optional)
   * @return Success
   */
  getTree(
    orgUnitNodeId: string | undefined,
    parentOrgUnitNodeId: string | undefined,
    filterText: string | undefined,
    sorting: string | undefined,
    maxResultCount: number | undefined,
    skipCount: number | undefined,
    cancelToken?: CancelToken
  ): Promise<ListApiResponse> {
    let url_ = this.baseUrl + "/api/OrgUnitNode/GetTree?";
    if (orgUnitNodeId === null)
      throw new Error("The parameter 'orgUnitNodeId' cannot be null.");
    else if (orgUnitNodeId !== undefined)
      url_ += "OrgUnitNodeId=" + encodeURIComponent("" + orgUnitNodeId) + "&";
    if (parentOrgUnitNodeId === null)
      throw new Error("The parameter 'parentOrgUnitNodeId' cannot be null.");
    else if (parentOrgUnitNodeId !== undefined)
      url_ +=
        "ParentOrgUnitNodeId=" +
        encodeURIComponent("" + parentOrgUnitNodeId) +
        "&";
    if (filterText === null)
      throw new Error("The parameter 'filterText' cannot be null.");
    else if (filterText !== undefined)
      url_ += "FilterText=" + encodeURIComponent("" + filterText) + "&";
    if (sorting === null)
      throw new Error("The parameter 'sorting' cannot be null.");
    else if (sorting !== undefined)
      url_ += "Sorting=" + encodeURIComponent("" + sorting) + "&";
    if (maxResultCount === null)
      throw new Error("The parameter 'maxResultCount' cannot be null.");
    else if (maxResultCount !== undefined)
      url_ += "MaxResultCount=" + encodeURIComponent("" + maxResultCount) + "&";
    if (skipCount === null)
      throw new Error("The parameter 'skipCount' cannot be null.");
    else if (skipCount !== undefined)
      url_ += "SkipCount=" + encodeURIComponent("" + skipCount) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetTree(_response);
      });
  }

  protected processGetTree(response: AxiosResponse): Promise<ListApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = ListApiResponse.fromJS(resultData200);
      return Promise.resolve<ListApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<ListApiResponse>(null as any);
  }
}

export class UserServiceProxy {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? "";
  }

  /**
   * @param body (optional)
   * @return Success - No return data
   */
  createUser(
    body: CreateOrUpdateUserParam | undefined,
    cancelToken?: CancelToken
  ): Promise<void> {
    let url_ = this.baseUrl + "/api/User/CreateUser";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCreateUser(_response);
      });
  }

  protected processCreateUser(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return Success - No return data
   */
  updateUser(
    body: CreateOrUpdateUserParam | undefined,
    cancelToken?: CancelToken
  ): Promise<void> {
    let url_ = this.baseUrl + "/api/User/UpdateUser";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "PUT",
      url: url_,
      headers: {
        "Content-Type": "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processUpdateUser(_response);
      });
  }

  protected processUpdateUser(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * 获取用户列表分页数据
   * @param body (optional)
   * @return Success
   */
  getPaged(
    body: GetUsersInput | undefined,
    cancelToken?: CancelToken
  ): Promise<GetPagedResultApiResponse> {
    let url_ = this.baseUrl + "/api/User/GetPaged";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetPaged(_response);
      });
  }

  protected processGetPaged(
    response: AxiosResponse
  ): Promise<GetPagedResultApiResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = GetPagedResultApiResponse.fromJS(resultData200);
      return Promise.resolve<GetPagedResultApiResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<GetPagedResultApiResponse>(null as any);
  }

  /**
   * @return Success
   */
  getUserColumnList(cancelToken?: CancelToken): Promise<ListApiResponse2> {
    let url_ = this.baseUrl + "/api/User/GetUserColumnList";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json"
      },
      cancelToken
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetUserColumnList(_response);
      });
  }

  protected processGetUserColumnList(
    response: AxiosResponse
  ): Promise<ListApiResponse2> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = ListApiResponse2.fromJS(resultData200);
      return Promise.resolve<ListApiResponse2>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      );
    }
    return Promise.resolve<ListApiResponse2>(null as any);
  }
}

export class AccountLoginDto implements IAccountLoginDto {
  /** 用户名 */
  userName: string;
  /** 密码 */
  password: string;
  /** 手机号 */
  phoneNumber: string | undefined;
  /** 客户端，PC，App */
  clientType: string | undefined;
  /** 记住我 */
  rememberMe: boolean;
  /** 是否刷新Token */
  isRefresh: boolean;
  /** 是否Api登录 */
  isApiLogin: boolean;

  constructor(data?: IAccountLoginDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.userName = _data["UserName"];
      this.password = _data["Password"];
      this.phoneNumber = _data["PhoneNumber"];
      this.clientType = _data["ClientType"];
      this.rememberMe = _data["RememberMe"];
      this.isRefresh = _data["IsRefresh"];
      this.isApiLogin = _data["IsApiLogin"];
    }
  }

  static fromJS(data: any): AccountLoginDto {
    data = typeof data === "object" ? data : {};
    let result = new AccountLoginDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["UserName"] = this.userName;
    data["Password"] = this.password;
    data["PhoneNumber"] = this.phoneNumber;
    data["ClientType"] = this.clientType;
    data["RememberMe"] = this.rememberMe;
    data["IsRefresh"] = this.isRefresh;
    data["IsApiLogin"] = this.isApiLogin;
    return data;
  }

  clone(): AccountLoginDto {
    const json = this.toJSON();
    let result = new AccountLoginDto();
    result.init(json);
    return result;
  }
}

export interface IAccountLoginDto {
  /** 用户名 */
  userName: string;
  /** 密码 */
  password: string;
  /** 手机号 */
  phoneNumber: string | undefined;
  /** 客户端，PC，App */
  clientType: string | undefined;
  /** 记住我 */
  rememberMe: boolean;
  /** 是否刷新Token */
  isRefresh: boolean;
  /** 是否Api登录 */
  isApiLogin: boolean;
}

export class AuthenticateResultModel implements IAuthenticateResultModel {
  /** 用户头像 */
  avatar: string | undefined;
  /** 用户名称 */
  userName: string | undefined;
  /** 用户昵称 */
  nickName: string | undefined;
  /** 用户角色 */
  roles: string[] | undefined;
  /** 用户权限 */
  permissions: string[] | undefined;
  /** 过期时间 */
  expires: moment.Moment;
  /** 加密后的密码 */
  password: string | undefined;
  accessToken: string | undefined;
  encryptedAccessToken: string | undefined;
  refreshToken: string | undefined;
  expireInSeconds: number;
  userId: string | undefined;
  shouldResetPassword: boolean;
  passwordResetCode: string | undefined;
  refreshTokenExpire: moment.Moment;
  returnUrl: string | undefined;
  waitingForActivation: boolean;

  constructor(data?: IAuthenticateResultModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.avatar = _data["Avatar"];
      this.userName = _data["UserName"];
      this.nickName = _data["NickName"];
      if (Array.isArray(_data["Roles"])) {
        this.roles = [] as any;
        for (let item of _data["Roles"]) this.roles.push(item);
      }
      if (Array.isArray(_data["Permissions"])) {
        this.permissions = [] as any;
        for (let item of _data["Permissions"]) this.permissions.push(item);
      }
      this.expires = _data["Expires"]
        ? moment(_data["Expires"].toString())
        : <any>undefined;
      this.password = _data["Password"];
      this.accessToken = _data["AccessToken"];
      this.encryptedAccessToken = _data["EncryptedAccessToken"];
      this.refreshToken = _data["RefreshToken"];
      this.expireInSeconds = _data["ExpireInSeconds"];
      this.userId = _data["UserId"];
      this.shouldResetPassword = _data["ShouldResetPassword"];
      this.passwordResetCode = _data["PasswordResetCode"];
      this.refreshTokenExpire = _data["RefreshTokenExpire"]
        ? moment(_data["RefreshTokenExpire"].toString())
        : <any>undefined;
      this.returnUrl = _data["ReturnUrl"];
      this.waitingForActivation = _data["WaitingForActivation"];
    }
  }

  static fromJS(data: any): AuthenticateResultModel {
    data = typeof data === "object" ? data : {};
    let result = new AuthenticateResultModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Avatar"] = this.avatar;
    data["UserName"] = this.userName;
    data["NickName"] = this.nickName;
    if (Array.isArray(this.roles)) {
      data["Roles"] = [];
      for (let item of this.roles) data["Roles"].push(item);
    }
    if (Array.isArray(this.permissions)) {
      data["Permissions"] = [];
      for (let item of this.permissions) data["Permissions"].push(item);
    }
    data["Expires"] = this.expires
      ? this.expires.toISOString()
      : <any>undefined;
    data["Password"] = this.password;
    data["AccessToken"] = this.accessToken;
    data["EncryptedAccessToken"] = this.encryptedAccessToken;
    data["RefreshToken"] = this.refreshToken;
    data["ExpireInSeconds"] = this.expireInSeconds;
    data["UserId"] = this.userId;
    data["ShouldResetPassword"] = this.shouldResetPassword;
    data["PasswordResetCode"] = this.passwordResetCode;
    data["RefreshTokenExpire"] = this.refreshTokenExpire
      ? this.refreshTokenExpire.toISOString()
      : <any>undefined;
    data["ReturnUrl"] = this.returnUrl;
    data["WaitingForActivation"] = this.waitingForActivation;
    return data;
  }

  clone(): AuthenticateResultModel {
    const json = this.toJSON();
    let result = new AuthenticateResultModel();
    result.init(json);
    return result;
  }
}

export interface IAuthenticateResultModel {
  /** 用户头像 */
  avatar: string | undefined;
  /** 用户名称 */
  userName: string | undefined;
  /** 用户昵称 */
  nickName: string | undefined;
  /** 用户角色 */
  roles: string[] | undefined;
  /** 用户权限 */
  permissions: string[] | undefined;
  /** 过期时间 */
  expires: moment.Moment;
  /** 加密后的密码 */
  password: string | undefined;
  accessToken: string | undefined;
  encryptedAccessToken: string | undefined;
  refreshToken: string | undefined;
  expireInSeconds: number;
  userId: string | undefined;
  shouldResetPassword: boolean;
  passwordResetCode: string | undefined;
  refreshTokenExpire: moment.Moment;
  returnUrl: string | undefined;
  waitingForActivation: boolean;
}

export class AuthenticateResultModelApiResponse
  implements IAuthenticateResultModelApiResponse
{
  data: AuthenticateResultModel | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IAuthenticateResultModelApiResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.data = _data["Data"]
        ? AuthenticateResultModel.fromJS(_data["Data"])
        : <any>undefined;
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): AuthenticateResultModelApiResponse {
    data = typeof data === "object" ? data : {};
    let result = new AuthenticateResultModelApiResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Data"] = this.data ? this.data.toJSON() : <any>undefined;
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): AuthenticateResultModelApiResponse {
    const json = this.toJSON();
    let result = new AuthenticateResultModelApiResponse();
    result.init(json);
    return result;
  }
}

export interface IAuthenticateResultModelApiResponse {
  data: AuthenticateResultModel | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class StringApiResponse implements IStringApiResponse {
  data: string | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IStringApiResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.data = _data["Data"];
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): StringApiResponse {
    data = typeof data === "object" ? data : {};
    let result = new StringApiResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Data"] = this.data;
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): StringApiResponse {
    const json = this.toJSON();
    let result = new StringApiResponse();
    result.init(json);
    return result;
  }
}

export interface IStringApiResponse {
  data: string | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class OrgUnitNodeEditDto implements IOrgUnitNodeEditDto {
  /** id */
  id: string | undefined;
  /** 名称 */
  name: string | undefined;
  parentIdList: string | undefined;
  parentId: string | undefined;

  constructor(data?: IOrgUnitNodeEditDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["Id"];
      this.name = _data["Name"];
      this.parentIdList = _data["ParentIdList"];
      this.parentId = _data["ParentId"];
    }
  }

  static fromJS(data: any): OrgUnitNodeEditDto {
    data = typeof data === "object" ? data : {};
    let result = new OrgUnitNodeEditDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Id"] = this.id;
    data["Name"] = this.name;
    data["ParentIdList"] = this.parentIdList;
    data["ParentId"] = this.parentId;
    return data;
  }

  clone(): OrgUnitNodeEditDto {
    const json = this.toJSON();
    let result = new OrgUnitNodeEditDto();
    result.init(json);
    return result;
  }
}

export interface IOrgUnitNodeEditDto {
  /** id */
  id: string | undefined;
  /** 名称 */
  name: string | undefined;
  parentIdList: string | undefined;
  parentId: string | undefined;
}

export class CreateOrUpdateOrgUnitNodeInput
  implements ICreateOrUpdateOrgUnitNodeInput
{
  orgUnitNode: OrgUnitNodeEditDto;

  constructor(data?: ICreateOrUpdateOrgUnitNodeInput) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
    if (!data) {
      this.orgUnitNode = new OrgUnitNodeEditDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.orgUnitNode = _data["OrgUnitNode"]
        ? OrgUnitNodeEditDto.fromJS(_data["OrgUnitNode"])
        : new OrgUnitNodeEditDto();
    }
  }

  static fromJS(data: any): CreateOrUpdateOrgUnitNodeInput {
    data = typeof data === "object" ? data : {};
    let result = new CreateOrUpdateOrgUnitNodeInput();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["OrgUnitNode"] = this.orgUnitNode
      ? this.orgUnitNode.toJSON()
      : <any>undefined;
    return data;
  }

  clone(): CreateOrUpdateOrgUnitNodeInput {
    const json = this.toJSON();
    let result = new CreateOrUpdateOrgUnitNodeInput();
    result.init(json);
    return result;
  }
}

export interface ICreateOrUpdateOrgUnitNodeInput {
  orgUnitNode: OrgUnitNodeEditDto;
}

export class EntityDto implements IEntityDto {
  id: string | undefined;

  constructor(data?: IEntityDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["Id"];
    }
  }

  static fromJS(data: any): EntityDto {
    data = typeof data === "object" ? data : {};
    let result = new EntityDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Id"] = this.id;
    return data;
  }

  clone(): EntityDto {
    const json = this.toJSON();
    let result = new EntityDto();
    result.init(json);
    return result;
  }
}

export interface IEntityDto {
  id: string | undefined;
}

export class OrgUnitNodeForEditOutput implements IOrgUnitNodeForEditOutput {
  orgUnitNode: OrgUnitNodeEditDto;

  constructor(data?: IOrgUnitNodeForEditOutput) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
    if (!data) {
      this.orgUnitNode = new OrgUnitNodeEditDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.orgUnitNode = _data["OrgUnitNode"]
        ? OrgUnitNodeEditDto.fromJS(_data["OrgUnitNode"])
        : new OrgUnitNodeEditDto();
    }
  }

  static fromJS(data: any): OrgUnitNodeForEditOutput {
    data = typeof data === "object" ? data : {};
    let result = new OrgUnitNodeForEditOutput();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["OrgUnitNode"] = this.orgUnitNode
      ? this.orgUnitNode.toJSON()
      : <any>undefined;
    return data;
  }

  clone(): OrgUnitNodeForEditOutput {
    const json = this.toJSON();
    let result = new OrgUnitNodeForEditOutput();
    result.init(json);
    return result;
  }
}

export interface IOrgUnitNodeForEditOutput {
  orgUnitNode: OrgUnitNodeEditDto;
}

export class OrgUnitNodeForEditOutputApiResponse
  implements IOrgUnitNodeForEditOutputApiResponse
{
  data: OrgUnitNodeForEditOutput | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IOrgUnitNodeForEditOutputApiResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.data = _data["Data"]
        ? OrgUnitNodeForEditOutput.fromJS(_data["Data"])
        : <any>undefined;
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): OrgUnitNodeForEditOutputApiResponse {
    data = typeof data === "object" ? data : {};
    let result = new OrgUnitNodeForEditOutputApiResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Data"] = this.data ? this.data.toJSON() : <any>undefined;
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): OrgUnitNodeForEditOutputApiResponse {
    const json = this.toJSON();
    let result = new OrgUnitNodeForEditOutputApiResponse();
    result.init(json);
    return result;
  }
}

export interface IOrgUnitNodeForEditOutputApiResponse {
  data: OrgUnitNodeForEditOutput | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class OrgUnitNodeListDto implements IOrgUnitNodeListDto {
  id: string | undefined;
  totalChild: number;

  constructor(data?: IOrgUnitNodeListDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["Id"];
      this.totalChild = _data["TotalChild"];
    }
  }

  static fromJS(data: any): OrgUnitNodeListDto {
    data = typeof data === "object" ? data : {};
    let result = new OrgUnitNodeListDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Id"] = this.id;
    data["TotalChild"] = this.totalChild;
    return data;
  }

  clone(): OrgUnitNodeListDto {
    const json = this.toJSON();
    let result = new OrgUnitNodeListDto();
    result.init(json);
    return result;
  }
}

export interface IOrgUnitNodeListDto {
  id: string | undefined;
  totalChild: number;
}

export class ListApiResponse implements IListApiResponse {
  data: OrgUnitNodeListDto[] | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IListApiResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["Data"])) {
        this.data = [] as any;
        for (let item of _data["Data"])
          this.data.push(OrgUnitNodeListDto.fromJS(item));
      }
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): ListApiResponse {
    data = typeof data === "object" ? data : {};
    let result = new ListApiResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    if (Array.isArray(this.data)) {
      data["Data"] = [];
      for (let item of this.data)
        data["Data"].push(item ? item.toJSON() : <any>undefined);
    }
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): ListApiResponse {
    const json = this.toJSON();
    let result = new ListApiResponse();
    result.init(json);
    return result;
  }
}

export interface IListApiResponse {
  data: OrgUnitNodeListDto[] | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class UserDto implements IUserDto {
  id: string | undefined;
  name: string | undefined;
  password: string | undefined;
  email: string | undefined;
  fullName: string | undefined;
  userName: string | undefined;
  phoneNumber: string | undefined;
  isActive: boolean;
  creationTime: moment.Moment;

  constructor(data?: IUserDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["Id"];
      this.name = _data["Name"];
      this.password = _data["Password"];
      this.email = _data["Email"];
      this.fullName = _data["FullName"];
      this.userName = _data["UserName"];
      this.phoneNumber = _data["PhoneNumber"];
      this.isActive = _data["IsActive"];
      this.creationTime = _data["CreationTime"]
        ? moment(_data["CreationTime"].toString())
        : <any>undefined;
    }
  }

  static fromJS(data: any): UserDto {
    data = typeof data === "object" ? data : {};
    let result = new UserDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Id"] = this.id;
    data["Name"] = this.name;
    data["Password"] = this.password;
    data["Email"] = this.email;
    data["FullName"] = this.fullName;
    data["UserName"] = this.userName;
    data["PhoneNumber"] = this.phoneNumber;
    data["IsActive"] = this.isActive;
    data["CreationTime"] = this.creationTime
      ? this.creationTime.toISOString()
      : <any>undefined;
    return data;
  }

  clone(): UserDto {
    const json = this.toJSON();
    let result = new UserDto();
    result.init(json);
    return result;
  }
}

export interface IUserDto {
  id: string | undefined;
  name: string | undefined;
  password: string | undefined;
  email: string | undefined;
  fullName: string | undefined;
  userName: string | undefined;
  phoneNumber: string | undefined;
  isActive: boolean;
  creationTime: moment.Moment;
}

export class CreateOrUpdateUserParam implements ICreateOrUpdateUserParam {
  id: number | undefined;
  /** 实体 */
  entity: UserDto | undefined;

  constructor(data?: ICreateOrUpdateUserParam) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.entity = _data["Entity"]
        ? UserDto.fromJS(_data["Entity"])
        : <any>undefined;
    }
  }

  static fromJS(data: any): CreateOrUpdateUserParam {
    data = typeof data === "object" ? data : {};
    let result = new CreateOrUpdateUserParam();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["Entity"] = this.entity ? this.entity.toJSON() : <any>undefined;
    return data;
  }

  clone(): CreateOrUpdateUserParam {
    const json = this.toJSON();
    let result = new CreateOrUpdateUserParam();
    result.init(json);
    return result;
  }
}

export interface ICreateOrUpdateUserParam {
  id: number | undefined;
  /** 实体 */
  entity: UserDto | undefined;
}

export class ColumnDto implements IColumnDto {
  /** 字段名称 */
  label: string | undefined;
  /** 字段key */
  prop: string | undefined;
  /** 指定插槽 */
  slot: string | undefined;

  constructor(data?: IColumnDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.label = _data["label"];
      this.prop = _data["prop"];
      this.slot = _data["slot"];
    }
  }

  static fromJS(data: any): ColumnDto {
    data = typeof data === "object" ? data : {};
    let result = new ColumnDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["label"] = this.label;
    data["prop"] = this.prop;
    data["slot"] = this.slot;
    return data;
  }

  clone(): ColumnDto {
    const json = this.toJSON();
    let result = new ColumnDto();
    result.init(json);
    return result;
  }
}

export interface IColumnDto {
  /** 字段名称 */
  label: string | undefined;
  /** 字段key */
  prop: string | undefined;
  /** 指定插槽 */
  slot: string | undefined;
}

export class UserListDto implements IUserListDto {
  /** 操作 */
  opertion: string | undefined;
  id: string | undefined;
  name: string | undefined;
  password: string | undefined;
  email: string | undefined;
  fullName: string | undefined;
  userName: string | undefined;
  phoneNumber: string | undefined;
  isActive: boolean;
  creationTime: moment.Moment;

  constructor(data?: IUserListDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.opertion = _data["Opertion"];
      this.id = _data["Id"];
      this.name = _data["Name"];
      this.password = _data["Password"];
      this.email = _data["Email"];
      this.fullName = _data["FullName"];
      this.userName = _data["UserName"];
      this.phoneNumber = _data["PhoneNumber"];
      this.isActive = _data["IsActive"];
      this.creationTime = _data["CreationTime"]
        ? moment(_data["CreationTime"].toString())
        : <any>undefined;
    }
  }

  static fromJS(data: any): UserListDto {
    data = typeof data === "object" ? data : {};
    let result = new UserListDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Opertion"] = this.opertion;
    data["Id"] = this.id;
    data["Name"] = this.name;
    data["Password"] = this.password;
    data["Email"] = this.email;
    data["FullName"] = this.fullName;
    data["UserName"] = this.userName;
    data["PhoneNumber"] = this.phoneNumber;
    data["IsActive"] = this.isActive;
    data["CreationTime"] = this.creationTime
      ? this.creationTime.toISOString()
      : <any>undefined;
    return data;
  }

  clone(): UserListDto {
    const json = this.toJSON();
    let result = new UserListDto();
    result.init(json);
    return result;
  }
}

export interface IUserListDto {
  /** 操作 */
  opertion: string | undefined;
  id: string | undefined;
  name: string | undefined;
  password: string | undefined;
  email: string | undefined;
  fullName: string | undefined;
  userName: string | undefined;
  phoneNumber: string | undefined;
  isActive: boolean;
  creationTime: moment.Moment;
}

export class PagedResultDto implements IPagedResultDto {
  totalCount: number;
  items: UserListDto[] | undefined;

  constructor(data?: IPagedResultDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.totalCount = _data["TotalCount"];
      if (Array.isArray(_data["Items"])) {
        this.items = [] as any;
        for (let item of _data["Items"])
          this.items.push(UserListDto.fromJS(item));
      }
    }
  }

  static fromJS(data: any): PagedResultDto {
    data = typeof data === "object" ? data : {};
    let result = new PagedResultDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["TotalCount"] = this.totalCount;
    if (Array.isArray(this.items)) {
      data["Items"] = [];
      for (let item of this.items)
        data["Items"].push(item ? item.toJSON() : <any>undefined);
    }
    return data;
  }

  clone(): PagedResultDto {
    const json = this.toJSON();
    let result = new PagedResultDto();
    result.init(json);
    return result;
  }
}

export interface IPagedResultDto {
  totalCount: number;
  items: UserListDto[] | undefined;
}

export class GetPagedResult implements IGetPagedResult {
  columns: ColumnDto[] | undefined;
  datas: PagedResultDto | undefined;

  constructor(data?: IGetPagedResult) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["columns"])) {
        this.columns = [] as any;
        for (let item of _data["columns"])
          this.columns.push(ColumnDto.fromJS(item));
      }
      this.datas = _data["datas"]
        ? PagedResultDto.fromJS(_data["datas"])
        : <any>undefined;
    }
  }

  static fromJS(data: any): GetPagedResult {
    data = typeof data === "object" ? data : {};
    let result = new GetPagedResult();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    if (Array.isArray(this.columns)) {
      data["columns"] = [];
      for (let item of this.columns)
        data["columns"].push(item ? item.toJSON() : <any>undefined);
    }
    data["datas"] = this.datas ? this.datas.toJSON() : <any>undefined;
    return data;
  }

  clone(): GetPagedResult {
    const json = this.toJSON();
    let result = new GetPagedResult();
    result.init(json);
    return result;
  }
}

export interface IGetPagedResult {
  columns: ColumnDto[] | undefined;
  datas: PagedResultDto | undefined;
}

export class GetPagedResultApiResponse implements IGetPagedResultApiResponse {
  data: GetPagedResult | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IGetPagedResultApiResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.data = _data["Data"]
        ? GetPagedResult.fromJS(_data["Data"])
        : <any>undefined;
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): GetPagedResultApiResponse {
    data = typeof data === "object" ? data : {};
    let result = new GetPagedResultApiResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Data"] = this.data ? this.data.toJSON() : <any>undefined;
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): GetPagedResultApiResponse {
    const json = this.toJSON();
    let result = new GetPagedResultApiResponse();
    result.init(json);
    return result;
  }
}

export interface IGetPagedResultApiResponse {
  data: GetPagedResult | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class GetUsersInput implements IGetUsersInput {
  filterText: string | undefined;
  sorting: string | undefined;
  maxResultCount: number;
  skipCount: number;

  constructor(data?: IGetUsersInput) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.filterText = _data["FilterText"];
      this.sorting = _data["Sorting"];
      this.maxResultCount = _data["MaxResultCount"];
      this.skipCount = _data["SkipCount"];
    }
  }

  static fromJS(data: any): GetUsersInput {
    data = typeof data === "object" ? data : {};
    let result = new GetUsersInput();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["FilterText"] = this.filterText;
    data["Sorting"] = this.sorting;
    data["MaxResultCount"] = this.maxResultCount;
    data["SkipCount"] = this.skipCount;
    return data;
  }

  clone(): GetUsersInput {
    const json = this.toJSON();
    let result = new GetUsersInput();
    result.init(json);
    return result;
  }
}

export interface IGetUsersInput {
  filterText: string | undefined;
  sorting: string | undefined;
  maxResultCount: number;
  skipCount: number;
}

export class ListApiResponse2 implements IListApiResponse2 {
  data: ColumnDto[] | undefined;
  code: number;
  success: boolean;
  message: string | undefined;

  constructor(data?: IListApiResponse2) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["Data"])) {
        this.data = [] as any;
        for (let item of _data["Data"]) this.data.push(ColumnDto.fromJS(item));
      }
      this.code = _data["Code"];
      this.success = _data["Success"];
      this.message = _data["Message"];
    }
  }

  static fromJS(data: any): ListApiResponse2 {
    data = typeof data === "object" ? data : {};
    let result = new ListApiResponse2();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    if (Array.isArray(this.data)) {
      data["Data"] = [];
      for (let item of this.data)
        data["Data"].push(item ? item.toJSON() : <any>undefined);
    }
    data["Code"] = this.code;
    data["Success"] = this.success;
    data["Message"] = this.message;
    return data;
  }

  clone(): ListApiResponse2 {
    const json = this.toJSON();
    let result = new ListApiResponse2();
    result.init(json);
    return result;
  }
}

export interface IListApiResponse2 {
  data: ColumnDto[] | undefined;
  code: number;
  success: boolean;
  message: string | undefined;
}

export class SwaggerException extends Error {
  message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isSwaggerException = true;

  static isSwaggerException(obj: any): obj is SwaggerException {
    return obj.isSwaggerException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new SwaggerException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}

// import "rxjs/add/operator/finally";
